name: doctor_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #state management
  flutter_bloc: ^8.1.4
  #Code generation for immutable classes
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  #Code generation for JSON serialization
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  #dependency injection
  get_it: ^7.6.7
  # Networking
  dio: ^5.4.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  #localiztion
  intl: ^0.18.1
  easy_localization: ^3.0.4
  #splash screen
  flutter_native_splash: ^2.3.13
  #google fonts
  google_fonts: ^6.1.0
  # screen utlis for responsive design
  flutter_screenutil: ^5.9.0
  #local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #shared preferences
  shared_preferences: ^2.2.2
  # svg picture
  flutter_svg: ^2.0.10+1
  #loading_indicator
  loading_indicator: ^3.1.1
  #url launch
  url_launcher: ^6.2.4
  # icons
  icons_plus: ^5.0.0
  # to auto generate code
  build_runner: ^2.4.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/

